
import React, { useEffect, useState } from 'react';
import { useLotStore, type Lot } from '@/stores/lotStore';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import LotDetail from '@/components/lots/LotDetail';
import LotForm from '@/components/lots/LotForm';
import LotMapView from '@/components/lots/LotMapView';
import LotsGrid from '@/components/lots/LotsGrid';
import CadastralMapView from '@/components/lots/CadastralMapView';
import { toast } from 'sonner';
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle,
  DialogClose
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { AlertTriangle } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { getPolygonDataForLots, syncAllLotAreasWithPolygons } from '@/services/lotPolygonService';
import { applySEO } from '@/utils/seo';

const Lots = () => {
  const { lots, loadLots, deleteLot, isLoading, setSelectedLot } = useLotStore();
  const [activeTab, setActiveTab] = useState('map');
  const [selectedLot, setSelectedLotState] = useState<Lot | null>(null);
  const [polygonData, setPolygonData] = useState<Array<{lotId: string; areaHectares?: number}>>([]);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [lotToDelete, setLotToDelete] = useState<string | null>(null);

  // SEO metadata for Lots page
  useEffect(() => {
    applySEO({
      title: 'Potreros — SKYRANCH',
      description: 'Gestiona potreros, dibuja polígonos y consulta el mapa catastral en SKYRANCH.',
      canonical: window.location.href
    });
  }, []);

  // Load lots and polygon data
  useEffect(() => {
    console.log('🔄 Loading lots and polygon data...');
    loadLots();
    loadPolygonData();
    
    // Sync polygon areas with lot sizes to ensure consistency
    syncAllLotAreasWithPolygons().then(success => {
      if (success) {
        console.log('✅ Successfully synchronized all lot areas with polygons');
      }
    });
  }, [loadLots]);

  const loadPolygonData = async () => {
    try {
      const data = await getPolygonDataForLots();
      setPolygonData(data);
    } catch (error) {
      console.error('❌ Error loading polygon data:', error);
    }
  };

  const handleLotSelect = (lotId: string) => {
    const lot = lots.find(l => l.id === lotId);
    if (lot) {
      setSelectedLotState(lot);
      setActiveTab('detail');
      setSelectedLot(lot);
    }
  };

  const handleCreateLot = () => {
    console.log('🔄 Opening manual lot creation form...');
    setShowCreateForm(true);
  };


  const handleDeleteLot = (lotId: string) => {
    setLotToDelete(lotId);
    setShowDeleteDialog(true);
  };

  const confirmDeleteLot = async () => {
    if (lotToDelete) {
      const success = await deleteLot(lotToDelete);
      if (success) {
        toast.success('Lote eliminado correctamente');
        setShowDeleteDialog(false);
        setLotToDelete(null);
        
        // If we were viewing the deleted lot, go back to map
        if (selectedLot?.id === lotToDelete) {
          setSelectedLotState(null);
          setActiveTab('map');
        }
      } else {
        toast.error('Error al eliminar el lote');
      }
    }
  };

  const handleFormClose = () => {
    setShowCreateForm(false);
    loadLots();
    loadPolygonData();
  };

  // Reload polygon data when on map tab
  useEffect(() => {
    if (activeTab === 'map') {
      loadPolygonData();
    }
  }, [activeTab]);

  return (
    <div className="page-with-logo">
      <div className="container mx-auto pb-6 px-2 md:px-4">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">Potreros</h1>
            <p className="text-gray-500">Administra tus potreros y datos catastrales</p>
          </div>
        </div>

        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="mb-6 flex flex-col sm:flex-row w-full sm:w-auto">
            
            <TabsTrigger value="map" className="w-full sm:w-auto">Potreros</TabsTrigger>
            <TabsTrigger value="cadastral" className="w-full sm:w-auto">Mapa Catastral</TabsTrigger>
            {selectedLot && <TabsTrigger value="detail" className="w-full sm:w-auto">Detalle</TabsTrigger>}
          </TabsList>
          
          
          <TabsContent value="map">
            <div className="flex items-center justify-between mb-4">
              <Button onClick={handleCreateLot}>Nuevo Potrero</Button>
            </div>
            <LotMapView 
              lots={lots}
              onLotSelect={handleLotSelect}
            />
            <div className="mt-6">
              <LotsGrid 
                lots={lots.filter(l => !(l as any).autoGenerated)}
                onLotSelect={handleLotSelect}
                onDeleteLot={handleDeleteLot}
                polygonData={polygonData}
              />
            </div>
          </TabsContent>

          <TabsContent value="cadastral">
            <CadastralMapView />
          </TabsContent>
          
          <TabsContent value="detail">
            {selectedLot && (
              <LotDetail 
                lot={selectedLot}
                onBack={() => {
                  setActiveTab('map');
                  setSelectedLotState(null);
                }}
              />
            )}
          </TabsContent>
        </Tabs>

        {/* Create Lot Dialog */}
        <Dialog open={showCreateForm} onOpenChange={setShowCreateForm}>
          <DialogContent className="max-w-3xl">
            <DialogHeader>
              <DialogTitle>Crear Nuevo Lote Manual</DialogTitle>
            </DialogHeader>
            <LotForm onClose={handleFormClose} />
          </DialogContent>
        </Dialog>
        
        <Dialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Confirmar Eliminación</DialogTitle>
            </DialogHeader>
            <Alert variant="destructive">
              <AlertTriangle className="h-4 w-4" />
              <AlertTitle>Advertencia</AlertTitle>
              <AlertDescription>
                ¿Estás seguro de que deseas eliminar este lote? Esta acción no se puede deshacer.
              </AlertDescription>
            </Alert>
            <div className="flex justify-end gap-2 mt-4">
              <DialogClose asChild>
                <Button variant="outline">Cancelar</Button>
              </DialogClose>
              <Button 
                variant="destructive" 
                onClick={confirmDeleteLot}
              >
                Eliminar
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
};

export default Lots;
