
import type { Animal } from '@/stores/animalStore';

// Helper function to transform database row to Animal interface
export const transformAnimalData = (data: any): Animal => {
  console.log('Transforming animal data:', data);
  
  const animal = {
    id: data.id,
    name: data.name || '',
    tag: data.tag || '',
    species: data.species || 'bovino',
    breed: data.breed || '',
    birthDate: data.birth_date || '',
    gender: data.gender || '',
    weight: data.weight ? data.weight.toString() : '',
    color: data.color || '',
    motherId: data.mother_id || '',
    fatherId: data.father_id || '',
    healthStatus: data.health_status || 'healthy',
    notes: data.notes || '',
    image: data.image_url || null,
    lifecycleStatus: data.lifecycle_status || 'active',
    dateOfDeath: data.date_of_death || '',
    causeOfDeath: data.cause_of_death || '',
    maternalGrandmotherId: data.maternal_grandmother_id || '',
    maternalGrandfatherId: data.maternal_grandfather_id || '',
    paternalGrandmotherId: data.paternal_grandmother_id || '',
    paternalGrandfatherId: data.paternal_grandfather_id || '',
    // Great-grandparent fields (3rd generation)
    maternalGreatGrandmotherMaternalId: data.maternal_great_grandmother_maternal_id || '',
    maternalGreatGrandfatherMaternalId: data.maternal_great_grandfather_maternal_id || '',
    maternalGreatGrandmotherPaternalId: data.maternal_great_grandmother_paternal_id || '',
    maternalGreatGrandfatherPaternalId: data.maternal_great_grandfather_paternal_id || '',
    paternalGreatGrandmotherMaternalId: data.paternal_great_grandmother_maternal_id || '',
    paternalGreatGrandfatherMaternalId: data.paternal_great_grandfather_maternal_id || '',
    paternalGreatGrandmotherPaternalId: data.paternal_great_grandmother_paternal_id || '',
    paternalGreatGrandfatherPaternalId: data.paternal_great_grandfather_paternal_id || '',
    // Generation 4 fields
    gen4PaternalGgggfP: data.gen4_paternal_ggggf_p || '',
    gen4PaternalGgggmP: data.gen4_paternal_ggggm_p || '',
    gen4PaternalGggmfP: data.gen4_paternal_gggmf_p || '',
    gen4PaternalGggmmP: data.gen4_paternal_gggmm_p || '',
    gen4PaternalGgfgfP: data.gen4_paternal_ggfgf_p || '',
    gen4PaternalGgfgmP: data.gen4_paternal_ggfgm_p || '',
    gen4PaternalGgmgfP: data.gen4_paternal_ggmgf_p || '',
    gen4PaternalGgmgmP: data.gen4_paternal_ggmgm_p || '',
    gen4MaternalGgggfM: data.gen4_maternal_ggggf_m || '',
    gen4MaternalGgggmM: data.gen4_maternal_ggggm_m || '',
    gen4MaternalGggmfM: data.gen4_maternal_gggmf_m || '',
    gen4MaternalGggmmM: data.gen4_maternal_gggmm_m || '',
    gen4MaternalGgfgfM: data.gen4_maternal_ggfgf_m || '',
    gen4MaternalGgfgmM: data.gen4_maternal_ggfgm_m || '',
    gen4MaternalGgmgfM: data.gen4_maternal_ggmgf_m || '',
    gen4MaternalGgmgmM: data.gen4_maternal_ggmgm_m || '',
    // Generation 5 fields
    gen5Paternal1: data.gen5_paternal_1 || '',
    gen5Paternal2: data.gen5_paternal_2 || '',
    gen5Paternal3: data.gen5_paternal_3 || '',
    gen5Paternal4: data.gen5_paternal_4 || '',
    gen5Paternal5: data.gen5_paternal_5 || '',
    gen5Paternal6: data.gen5_paternal_6 || '',
    gen5Paternal7: data.gen5_paternal_7 || '',
    gen5Paternal8: data.gen5_paternal_8 || '',
    gen5Paternal9: data.gen5_paternal_9 || '',
    gen5Paternal10: data.gen5_paternal_10 || '',
    gen5Paternal11: data.gen5_paternal_11 || '',
    gen5Paternal12: data.gen5_paternal_12 || '',
    gen5Paternal13: data.gen5_paternal_13 || '',
    gen5Paternal14: data.gen5_paternal_14 || '',
    gen5Paternal15: data.gen5_paternal_15 || '',
    gen5Paternal16: data.gen5_paternal_16 || '',
    gen5Maternal1: data.gen5_maternal_1 || '',
    gen5Maternal2: data.gen5_maternal_2 || '',
    gen5Maternal3: data.gen5_maternal_3 || '',
    gen5Maternal4: data.gen5_maternal_4 || '',
    gen5Maternal5: data.gen5_maternal_5 || '',
    gen5Maternal6: data.gen5_maternal_6 || '',
    gen5Maternal7: data.gen5_maternal_7 || '',
    gen5Maternal8: data.gen5_maternal_8 || '',
    gen5Maternal9: data.gen5_maternal_9 || '',
    gen5Maternal10: data.gen5_maternal_10 || '',
    gen5Maternal11: data.gen5_maternal_11 || '',
    gen5Maternal12: data.gen5_maternal_12 || '',
    gen5Maternal13: data.gen5_maternal_13 || '',
    gen5Maternal14: data.gen5_maternal_14 || '',
    gen5Maternal15: data.gen5_maternal_15 || '',
    gen5Maternal16: data.gen5_maternal_16 || '',
  };

  console.log('Transformed animal:', animal);
  return animal;
};
