
import type { Animal } from '@/stores/animalStore';

// Helper function to transform database row to Animal interface
export const transformAnimalData = (data: any): Animal => {
  console.log('Transforming animal data:', data);
  
  const animal = {
    id: data.id,
    name: data.name || '',
    tag: data.tag || '',
    species: data.species || 'bovino',
    breed: data.breed || '',
    birthDate: data.birth_date || '',
    gender: data.gender || '',
    weight: data.weight ? data.weight.toString() : '',
    color: data.color || '',
    motherId: data.mother_id || '',
    fatherId: data.father_id || '',
    healthStatus: data.health_status || 'healthy',
    notes: data.notes || '',
    image: data.image_url || null,
    lifecycleStatus: data.lifecycle_status || 'active',
    dateOfDeath: data.date_of_death || '',
    causeOfDeath: data.cause_of_death || '',
    maternal_grandmother_id: data.maternal_grandmother_id || '',
    maternal_grandfather_id: data.maternal_grandfather_id || '',
    paternal_grandmother_id: data.paternal_grandmother_id || '',
    paternal_grandfather_id: data.paternal_grandfather_id || '',
    // Great-grandparent fields (3rd generation)
    maternal_great_grandmother_maternal_id: data.maternal_great_grandmother_maternal_id || '',
    maternal_great_grandfather_maternal_id: data.maternal_great_grandfather_maternal_id || '',
    maternal_great_grandmother_paternal_id: data.maternal_great_grandmother_paternal_id || '',
    maternal_great_grandfather_paternal_id: data.maternal_great_grandfather_paternal_id || '',
    paternal_great_grandmother_maternal_id: data.paternal_great_grandmother_maternal_id || '',
    paternal_great_grandfather_maternal_id: data.paternal_great_grandfather_maternal_id || '',
    paternal_great_grandmother_paternal_id: data.paternal_great_grandmother_paternal_id || '',
    paternal_great_grandfather_paternal_id: data.paternal_great_grandfather_paternal_id || '',
    // Generation 4 fields
    gen4_paternal_ggggf_p: data.gen4_paternal_ggggf_p || '',
    gen4_paternal_ggggm_p: data.gen4_paternal_ggggm_p || '',
    gen4_paternal_gggmf_p: data.gen4_paternal_gggmf_p || '',
    gen4_paternal_gggmm_p: data.gen4_paternal_gggmm_p || '',
    gen4_paternal_ggfgf_p: data.gen4_paternal_ggfgf_p || '',
    gen4_paternal_ggfgm_p: data.gen4_paternal_ggfgm_p || '',
    gen4_paternal_ggmgf_p: data.gen4_paternal_ggmgf_p || '',
    gen4_paternal_ggmgm_p: data.gen4_paternal_ggmgm_p || '',
    gen4_maternal_ggggf_m: data.gen4_maternal_ggggf_m || '',
    gen4_maternal_ggggm_m: data.gen4_maternal_ggggm_m || '',
    gen4_maternal_gggmf_m: data.gen4_maternal_gggmf_m || '',
    gen4_maternal_gggmm_m: data.gen4_maternal_gggmm_m || '',
    gen4_maternal_ggfgf_m: data.gen4_maternal_ggfgf_m || '',
    gen4_maternal_ggfgm_m: data.gen4_maternal_ggfgm_m || '',
    gen4_maternal_ggmgf_m: data.gen4_maternal_ggmgf_m || '',
    gen4_maternal_ggmgm_m: data.gen4_maternal_ggmgm_m || '',
    // Generation 5 fields
    gen5_paternal_1: data.gen5_paternal_1 || '',
    gen5_paternal_2: data.gen5_paternal_2 || '',
    gen5_paternal_3: data.gen5_paternal_3 || '',
    gen5_paternal_4: data.gen5_paternal_4 || '',
    gen5_paternal_5: data.gen5_paternal_5 || '',
    gen5_paternal_6: data.gen5_paternal_6 || '',
    gen5_paternal_7: data.gen5_paternal_7 || '',
    gen5_paternal_8: data.gen5_paternal_8 || '',
    gen5_paternal_9: data.gen5_paternal_9 || '',
    gen5_paternal_10: data.gen5_paternal_10 || '',
    gen5_paternal_11: data.gen5_paternal_11 || '',
    gen5_paternal_12: data.gen5_paternal_12 || '',
    gen5_paternal_13: data.gen5_paternal_13 || '',
    gen5_paternal_14: data.gen5_paternal_14 || '',
    gen5_paternal_15: data.gen5_paternal_15 || '',
    gen5_paternal_16: data.gen5_paternal_16 || '',
    gen5_maternal_1: data.gen5_maternal_1 || '',
    gen5_maternal_2: data.gen5_maternal_2 || '',
    gen5_maternal_3: data.gen5_maternal_3 || '',
    gen5_maternal_4: data.gen5_maternal_4 || '',
    gen5_maternal_5: data.gen5_maternal_5 || '',
    gen5_maternal_6: data.gen5_maternal_6 || '',
    gen5_maternal_7: data.gen5_maternal_7 || '',
    gen5_maternal_8: data.gen5_maternal_8 || '',
    gen5_maternal_9: data.gen5_maternal_9 || '',
    gen5_maternal_10: data.gen5_maternal_10 || '',
    gen5_maternal_11: data.gen5_maternal_11 || '',
    gen5_maternal_12: data.gen5_maternal_12 || '',
    gen5_maternal_13: data.gen5_maternal_13 || '',
    gen5_maternal_14: data.gen5_maternal_14 || '',
    gen5_maternal_15: data.gen5_maternal_15 || '',
    gen5_maternal_16: data.gen5_maternal_16 || '',
  };

  console.log('Transformed animal:', animal);
  return animal;
};
