
import React, { useEffect } from 'react';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Building, MapPin, Trash2, Users, Calendar, Leaf, Info } from 'lucide-react';
import { type Lot, useLotStore } from '@/stores/lotStore';
import LotAreaDisplay from './LotAreaDisplay';
import InlineLotNameEditor from './InlineLotNameEditor';
import { useTimezone } from '@/hooks/useTimezone';

interface LotCardProps {
  lot: Lot;
  onSelect: (lotId: string) => void;
  onDelete: (lotId: string) => void;
  polygonData?: Array<{lotId: string; areaHectares?: number}>;
  allLots?: Lot[]; // Added to detect duplicates
}

const LotCard: React.FC<LotCardProps> = ({ lot, onSelect, onDelete, polygonData, allLots = [] }) => {
  const { loadGrazingMetrics, getGrazingMetrics } = useLotStore();
  const { formatDateTime } = useTimezone();
  
  // Load grazing metrics for this lot to get the expected exit date
  useEffect(() => {
    if (lot.currentAnimals && lot.currentAnimals > 0) {
      loadGrazingMetrics(lot.id);
    }
  }, [lot.id, lot.currentAnimals, loadGrazingMetrics]);
  
  const grazingMetrics = getGrazingMetrics(lot.id);
  const getStatusColor = (status: string, currentAnimals?: number, capacity?: number) => {
    // Dynamic status based on animals and capacity
    if (currentAnimals && currentAnimals > 0) {
      return 'bg-blue-100 text-blue-800'; // En Uso
    } else if (status === 'resting') {
      return 'bg-yellow-100 text-yellow-800'; // En Descanso
    } else {
      return 'bg-green-100 text-green-800'; // Disponible
    }
  };

  const getCardBackgroundColor = (status: string, currentAnimals?: number, capacity?: number) => {
    // Card background based on status
    if (currentAnimals && currentAnimals > 0) {
      return 'bg-blue-50 border-blue-200'; // En Uso - light blue
    } else if (status === 'resting') {
      return 'bg-yellow-50 border-yellow-200'; // En Descanso - light yellow
    } else {
      return 'bg-green-50 border-green-200'; // Disponible - light green
    }
  };

  const getStatusText = (status: string, currentAnimals?: number, capacity?: number) => {
    // Dynamic status based on animals and capacity
    if (currentAnimals && currentAnimals > 0) {
      return 'En Uso';
    } else if (status === 'resting') {
      return 'En Descanso';
    } else {
      return 'Disponible';
    }
  };

  const isAutoGenerated = lot.autoGenerated === true;
  const lotType = isAutoGenerated ? 'property' : 'pasture';
  const polygonArea = polygonData?.find(p => p.lotId === lot.id)?.areaHectares;
  
  // Check for duplicate lot names
  const duplicateLots = allLots.filter(l => l.name === lot.name && l.id !== lot.id);
  const hasDuplicates = duplicateLots.length > 0;

  return (
    <Card className={`hover:shadow-md transition-shadow cursor-pointer border-2 ${getCardBackgroundColor(lot.status, lot.currentAnimals, lot.capacity)}`}>
      <CardHeader className="px-4 pb-3 sm:px-5">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-2 flex-1 min-w-0">
            {isAutoGenerated ? (
              <Building className="w-4 h-4 text-gray-500 shrink-0" />
            ) : (
              <Leaf className="w-4 h-4 text-green-500 shrink-0" />
            )}
            <div className="flex-1 min-w-0">
              {isAutoGenerated ? (
                <h3 className="text-sm font-medium text-gray-900 truncate" title={lot.name}>
                  {lot.name}
                </h3>
              ) : (
                <InlineLotNameEditor
                  lotId={lot.id}
                  lotName={lot.name}
                  showEditIcon={true}
                />
              )}
            </div>
          </div>
          <div className="flex items-center gap-1 shrink-0">
            <Badge variant="secondary" className={getStatusColor(lot.status, lot.currentAnimals, lot.capacity)}>
              {getStatusText(lot.status, lot.currentAnimals, lot.capacity)}
            </Badge>
            {!isAutoGenerated && (
              <Button
                variant="ghost"
                size="sm"
                onClick={(e) => {
                  e.stopPropagation();
                  onDelete(lot.id);
                }}
                className="h-6 w-6 p-0 text-red-500 hover:text-red-700"
              >
                <Trash2 className="w-3 h-3" />
              </Button>
            )}
          </div>
        </div>
        
        {/* Duplicate warning and lot info */}
        {hasDuplicates && (
          <div className="flex items-center gap-1 text-xs text-amber-600 mt-1">
            <Info className="w-3 h-3" />
            <span>Hay {duplicateLots.length + 1} lotes con este nombre</span>
          </div>
        )}
      </CardHeader>
      
      <CardContent className="pt-0 px-4 sm:px-5" onClick={() => onSelect(lot.id)}>
        <div className="space-y-2 text-sm text-gray-600">
          <LotAreaDisplay 
            lot={lot}
            polygonArea={polygonArea}
            showPolygonHint={!isAutoGenerated}
          />
          
          {lot.capacity && (
            <div className="flex items-center gap-1">
              <Users className="w-3 h-3" />
              <span>Capacidad: {lot.capacity} animales</span>
            </div>
          )}
          
          {typeof lot.capacity === 'number' && lot.capacity > 0 && (
            <div className="flex items-center gap-1">
              <Users className="w-3 h-3" />
              <span>Ocupación: {Math.round(((lot.currentAnimals || 0) / lot.capacity) * 100)}%</span>
            </div>
          )}
          
          {lot.currentAnimals && lot.currentAnimals > 0 && grazingMetrics?.expectedExitDate && (
            <div className="flex items-center gap-1">
              <Calendar className="w-3 h-3" />
              <span>Salida sugerida: {new Date(grazingMetrics.expectedExitDate).toLocaleDateString()}</span>
            </div>
          )}
          
          {lot.lastRotationDate && (
            <div className="flex items-center gap-1">
              <Calendar className="w-3 h-3" />
              <span>Última rotación: {new Date(lot.lastRotationDate).toLocaleDateString()}</span>
            </div>
          )}
          
          {lot.description && (
            <p className="text-xs text-gray-500 line-clamp-2">
              {lot.description}
            </p>
          )}
          
          {/* Show creation info for user-created lots or when there are duplicates */}
          {(!isAutoGenerated || hasDuplicates) && (
            <div className="pt-2 border-t border-gray-100 mt-2">
              <div className="text-xs text-gray-500">
                <div className="flex items-center justify-between">
                  <span>Tipo: {isAutoGenerated ? 'Propiedad' : 'Pastoreo'}</span>
                  {lot.createdAt && (
                    <span>{formatDateTime(lot.createdAt)}</span>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};

export default LotCard;
