
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { MapPin, Users, Activity, BarChart3 } from 'lucide-react';
import { type Lot } from '@/stores/lotStore';

interface PolygonData {
  lotId: string;
  areaHectares?: number;
}

interface LotStatisticsProps {
  lots: Lot[];
  polygonData?: PolygonData[];
  propiedadParcelsCount: number;
}

const LotStatistics = ({ lots, polygonData = [], propiedadParcelsCount }: LotStatisticsProps) => {
  const totalAnimals = lots.reduce((sum, lot) => sum + (lot.currentAnimals || 0), 0);
  const totalCapacity = lots.reduce((sum, lot) => sum + (lot.capacity || 0), 0);
  const activePastureLots = lots.filter(l => l.status === 'active' && l.lotType === 'pasture').length;
  const manualLots = lots.filter(l => !l.autoGenerated);
  const manualLotPolygonData = polygonData.filter(p => {
    const lot = lots.find(l => l.id === p.lotId);
    return lot && !lot.autoGenerated;
  });
  const totalManualPastureArea = manualLotPolygonData.reduce((sum, p) => sum + (p.areaHectares || 0), 0);

  const formatArea = (areaHectares: number): string => {
    if (areaHectares < 0.01) {
      return `${(areaHectares * 10000).toFixed(0)} m²`;
    }
    return `${areaHectares.toFixed(1)} ha`;
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
      <Card>
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle className="text-sm font-medium">Parcelas PROPIEDAD</CardTitle>
          <MapPin className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{propiedadParcelsCount}</div>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle className="text-sm font-medium">Lotes Activos</CardTitle>
          <Activity className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{activePastureLots}</div>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle className="text-sm font-medium">Animales Asignados</CardTitle>
          <Users className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">{totalAnimals}</div>
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle className="text-sm font-medium">
            {totalManualPastureArea > 0 ? 'Área Calculada' : 'Capacidad Total'}
          </CardTitle>
          <BarChart3 className="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div className="text-2xl font-bold">
            {totalManualPastureArea > 0 ? formatArea(totalManualPastureArea) : totalCapacity}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default LotStatistics;
